name: sloth
repository: https://github.com/ynnob/sloth

ide:
  intellij:
    enabled: false

packages:
  - .
  - packages/*

scripts:
  upgrade:
    run: dart pub upgrade
    exec:
      concurrency: 1

  build:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    select-package:
      depends-on: build_runner

  analyze:
    run: dart analyze . --fatal-infos
    exec:
      concurrency: 1
    description: Run dart analyzer in a specific package.
    select-package:
      ignore:
        - "*monorepo*"

  test:
    description: Run tests in a specific package.
    run: dart test --reporter expanded
    exec:
      concurrency: 1
    select-package:
      dir-exists:
        - "test/"
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: true

  format: dart format -o write .

  format-check:
    exec: flutter format . --set-exit-if-changed
    description: Run `flutter format` checks for all packages.

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
  # activate new bootstrapping mechanism
  bootstrap:
    usePubspecOverrides: true
