name: sloth
description: Sloth combines all current and future packages provided under the sloth name. You can import sloth to have access to all class extensions or add the individual packages to your pubspec.yaml file.
version: 1.0.1
homepage: https://ynnob.com
repository: https://github.com/ynnob/sloth

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  sloth_datetime: ^1.0.0
  sloth_link_crawler: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
