name: sloth_link_crawler
description: (WIP!) Web crawler to crawl all links of a website. Looking foward to respect robots.txt and use custom user agents.
version: 0.0.1
homepage: https://ynnob.com
repository: https://github.com/ynnob/sloth/tree/master/packages/sloth_link_crawler

environment:
  sdk: ">=2.18.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
